### ISSUE TITLE
If I have two buttons with mwlConfirmationPopOver directive why do two confirmation window popup?

### ISSUE THREAD

**Issue by raghubala** [mattlewis92/angular-confirmation-popover#29]
<button 
                                id="monthly-report"
                                class="btn btn-primary" 
                                mwlConfirmationPopover
                                [title]="title"
                                [message]="mmessage"
                                [confirmText]="confirmText"
                                [cancelText]="cancelText"                                 
                                placement="left"
                                (confirm)="mconfirmClicked = true; createMonthly(calYear,calMonth);"
                                (cancel)="mcancelClicked = true"
                                [(isOpen)]="isOpen"
                            >
                            Create Monthly
                        </button>

                        <button 
                                id="quarterly-report"
                                class="btn btn-primary" 
                                mwlConfirmationPopover
                                [title]="title"
                                [message]="qmessage"
                                [confirmText]="confirmText"
                                [cancelText]="cancelText"                                
                                placement="left"
                                (confirm)="qconfirmClicked = true; createMonthly(calYear,calMonth);"
                                (cancel)="qcancelClicked = true"
                                [(isOpen)]="isOpen"
                            >
                            Create Quarterly
                        </button>

**Comment by mattlewis92** [comment]
It's because `[(isOpen)]="isOpen"` is 2 way bound - when one popover is opened `isOpen` becomes true and opens the other popover.
