### ISSUE TITLE
Can't get to work

### ISSUE THREAD

**Issue by invious** [mattlewis92/angular-confirmation-popover#31]
new to Angular 2, apologies. Chose adding a popover to my page as my first task -- apologies again.

I was coming across this error when loading the Angular 2 app after following your setup instructions:

```
9:32 Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:7000/angular/static/app/app.module.js:21:38)
```

which was this line: `var angular_confirmation_popover_1 = require('angular-confirmation-popover');`

so eventually I figured out maybe I had to do something in this `systemjs.config.js` file. I added this line:

```
map: {
  'angular-confirmation-popover': 'npm:angular-confirmation-popover/dist/umd/angular-confirmation-popover.js'
```

and lo the Angular app worked again. Trying out the popover:

![image](https://cloud.githubusercontent.com/assets/1996089/20771397/3d699fbc-b717-11e6-85e4-1cefbb7893f2.png)

![image](https://cloud.githubusercontent.com/assets/1996089/20771404/422905e2-b717-11e6-89df-3e6c590e0e42.png)

Doesn't look much like a popover, am I missing some CSS? Have I screwed up something?

**Comment by mattlewis92** [comment]
Ah, looks like I've forgotten to mention in the readme that bootstrap is required, which I guess you'll not be including in your project. Best thing I can recommend is to copy paste the bootstrap CSS popover classes and theme them up to match material design.

**Comment by invious** [comment]
Is it normal to have to add the mapping to the `systemjs.js` manually?

**Comment by mattlewis92** [comment]
I'm no expert in system.js but I think so, it seems to be one of the major pain points that you need to manually configure every dependencies mapping.

**Comment by invious** [comment]
Is this sufficient to add to get this to work? https://cdnjs.com/libraries/webui-popover

**Comment by mattlewis92** [comment]
I think that requires jquery, you just need the bootstrap popover CSS
