### ISSUE TITLE
Popover size problem

### ISSUE THREAD

**Issue by ht89** [mattlewis92/angular-confirmation-popover#32]
Hello @mattlewis92,
how are you? the confirmation popover width and height are not right when clicking a button on a modal as shown in the link below. Would you please recommend a solution to it? Thank you a lot.

[https://www.dropbox.com/s/i1io68r9j9z7o0n/modal%20%26%20popover.png?dl=0](https://www.dropbox.com/s/i1io68r9j9z7o0n/modal%20%26%20popover.png?dl=0)

**Comment by mattlewis92** [comment]
Try appending the popover to the body instead of the element in the modal with this option: https://mattlewis92.github.io/angular-confirmation-popover/docs/classes/confirmationpopover.html#appendtobody

e.g.
```
[appendToBody]="true"
```

**Comment by ht89** [comment]
I appreciate your fast response. Your recommendation fixes the problem.
