### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by grosem** [mattlewis92/angular-confirmation-popover#33]
Hey,

thanks for your work. Any plans to allow localisation of the cancel/confirm buttons?

**Comment by mattlewis92** [comment]
This is already possible through the [confirmText](https://mattlewis92.github.io/angular-confirmation-popover/docs/classes/confirmationpopover.html#confirmtext) and [cancelText](https://mattlewis92.github.io/angular-confirmation-popover/docs/classes/confirmationpopover.html#canceltext) options. Hope that helps! 😃

**Comment by grosem** [comment]
Not sure how I missed that... thanks!

Matt Lewis <notifications@github.com> schrieb am So. 18. Dez. 2016 um 22:44:
