### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ltemimi** [mattlewis92/angular-confirmation-popover#37]
Hi

Since I set up as per instruction angular-confirmation-popover I get the error below shown on the console
I tried different versions to no avail. please help

Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	Evaluating http://localhost:14601/core-js
	Error loading http://localhost:14601/app/main.js
	    at eval (<anonymous>)
	Evaluating http://localhost:14601/core-js
	Error loading http://localhost:14601/app/main.js
(anonymous) @ index.html:29

regards Laz

**Comment by mattlewis92** [comment]
It sounds like your system.js mapping isn't set correctly, make sure this module is configured to point to `https://unpkg.com/angular-confirmation-popover@2.1.2/dist/umd/angular-confirmation-popover.js`

If you're still stuck make a repo that reproduces your problem and I'd be happy to dig in further, otherwise I'm just guessing 😃

**Comment by ltemimi** [comment]
Hi Matt
I have corrected the system to point to the correct popover js now I have the following error and I do not use webpack
Uncaught TypeError: Cannot read property 'core' of undefined    at webpackUniversalModuleDefinition (angular-confirmation-popover.js:9)    at angular-confirmation-popover.js:10webpackUniversalModuleDefinition @ angular-confirmation-popover.js:9(anonymous) @ angular-confirmation-popover.js:10
regards Laz ===================================Laz Temimi Automation & Control Engineer Tel.: 01733 810 068 Mobile: 07810 714 788 =================================== 

    On Thursday, 26 January 2017, 18:21, Matt Lewis <notifications@github.com> wrote:
 

 It sounds like your system.js mapping isn't set correctly, make sure this module is configured to point to https://unpkg.com/angular-confirmation-popover@2.1.2/dist/umd/angular-confirmation-popover.jsIf you're still stuck make a repo that reproduces your problem and I'd be happy to dig in further, otherwise I'm just guessing 😃 —

**Comment by mattlewis92** [comment]
That error is because this lib is trying to load angular from the `ng.core` global which doesn't seem to be available. It sounds like your system.js config is misconfigured.

**Comment by ltemimi** [comment]
Hi Matt
if I take off the angular-confirmation-popover all works well i.e the website, database access work great.so it appear specific to the popover, is it worth trying a different version?thanks laz ===================================Laz Temimi Automation & Control Engineer Tel.: 01733 810 068 Mobile: 07810 714 788 =================================== 

    On Thursday, 26 January 2017, 19:08, Matt Lewis <notifications@github.com> wrote:
 

 That error is because this lib is trying to load angular from the ng.core global which doesn't seem to be available. It sounds like your system.js config is misconfigured.—

**Comment by ltemimi** [comment]
Hi Matt
please find attached my systemjs.config. Could you spot any thing?
regards Laz ===================================Laz Temimi Automation & Control Engineer Tel.: 01733 810 068 Mobile: 07810 714 788 =================================== 

    On Thursday, 26 January 2017, 19:08, Matt Lewis <notifications@github.com> wrote:
 

 That error is because this lib is trying to load angular from the ng.core global which doesn't seem to be available. It sounds like your system.js config is misconfigured.—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.  

   
﻿// ReSharper disable once UnusedParameter
(function (global) {
    // map tells the System loader where to look for things
    var map = {
        'app': 'app', // our application files
        '@angular': 'js/@angular', // angular2 packages
        'rxjs': 'js/rxjs' // Rxjs package
    };

    // packages tells the System loader which filename and/or extensions to look for by default (when none are specified)
    var packages = {
        'app': { main: 'main.js', defaultExtension: 'js' },
        'rxjs': { defaultExtension: 'js' }
    };

    // configure @angular packages
    var ngPackageNames = [
       'common',
      'compiler',
      'core',
      'http',
      'platform-browser',
      'platform-browser-dynamic',
      'upgrade',
      'forms',
      'router'
    ];

    function packIndex(pkgName) {
        packages['@angular/' + pkgName] = { main: 'index.js', defaultExtension: 'js' };
    }

    function packUmd(pkgName) {
        packages['@angular/' + pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
    }

    var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
    ngPackageNames.forEach(setPackageConfig);
    var config = {
        map: map,
        packages: packages
    };
    System.config(config);
// ReSharper disable once ThisInGlobalContext
})(this);

**Comment by mattlewis92** [comment]
I'm unsure from that what the problem is, the only way to tell would be with a runnable repo. Here's a plunker which shows this module working with system.js, maybe it can help you find your issue: http://plnkr.co/edit/HBgmKYVfTJjxUe1wkg49?p=preview

**Comment by ltemimi** [comment]
Hi Matt
I managed to get it to work thanks to your kind help. The answer is simple it works when using a bundle but it doesnot work if referenced from index.html. So I could not use it without a bundle.
it is a wonderful piece of software it has helped me a lot
kind regards Laz ===================================Laz Temimi Automation & Control Engineer Tel.: 01733 810 068 Mobile: 07810 714 788 =================================== 

    On Thursday, 26 January 2017, 22:06, Matt Lewis <notifications@github.com> wrote:
 

 I'm unsure from that what the problem is, the only way to tell would be with a runnable repo. Here's a plunker which shows this module working with system.js, maybe it can help you find your issue: http://plnkr.co/edit/HBgmKYVfTJjxUe1wkg49?p=preview—
