### ISSUE TITLE
Popover out of screen

### ISSUE THREAD

**Issue by TeodorKolev** [mattlewis92/angular-confirmation-popover#38]
Popover behaves like here: http://plnkr.co/edit/s22zd8Qv9LxghtIjniHi?p=preview
it should behave like here: http://plnkr.co/edit/jLThSTrLUapAG8OLW44m?p=preview
Maybe it must be set parameter likepopover-append-to-body="true"

**Comment by mattlewis92** [comment]
Sorry I'm a bit confused, the examples you gave are for angular 1.x and this module is for angular 2+. There is an `appendToBody` option in this lib as well: https://mattlewis92.github.io/angular-confirmation-popover/docs/classes/confirmationpopover.html#appendtobody

**Comment by TeodorKolev** [comment]
I do not want to load boostrap.js. I use angular 2. Your popover is out of screen. Any remedy?

**Comment by mattlewis92** [comment]
This lib doesn't have a dependency on bootstraps js files. In the example you gave the popover appears off screen because the button is in the top left of the screen and the popover is set to appear to the left of it. The only way to get around that is to add more padding to the button or set the placement to somewhere else.

**Comment by TeodorKolev** [comment]
Not true at all. In bootstrap there is `popover-append-to-body="true"` that makes popup content to be set to body.

**Comment by TeodorKolev** [comment]
I have follow the instructions but `[appendToBody]="true"` did not working. How can I make it works?

**Comment by mattlewis92** [comment]
If you inspect element on the demo you can see the popover is appended to the body...
![screen shot 2017-01-27 at 11 35 40](https://cloud.githubusercontent.com/assets/6425649/22369596/c805043c-e484-11e6-9257-5c4a7f0ed328.png)

**Comment by TeodorKolev** [comment]
Please float button to left. You can try with Show on bottom. If you float it to left content is out of screen. I suppose to not be!

**Comment by mattlewis92** [comment]
Sorry I don't follow you, please can you show me what you mean on a plunker? You can use this as a starting point: http://plnkr.co/edit/HBgmKYVfTJjxUe1wkg49?p=preview

**Comment by TeodorKolev** [comment]
Remove classes `container text-center` from holder div. Click button

**Comment by TeodorKolev** [comment]
![capture](https://cloud.githubusercontent.com/assets/10398337/22370030/e955baf6-e497-11e6-8ab1-3cdba2be7000.PNG)

**Comment by mattlewis92** [comment]
That's as expected, the popover goes off screen as there is no where else to place it. This is how bootstrap works. To fix this you'd adjust the placement to be on the right or add padding around the button.

**Comment by TeodorKolev** [comment]
[](http://newyork2017.findevr.com/#partners) example of proper bootstrap behavior. You can check in smaller resolutions.

**Comment by mattlewis92** [comment]
That site is using custom logic to workaround it, native bootstrap doesn't do this:
![screen shot 2017-01-27 at 11 58 35](https://cloud.githubusercontent.com/assets/6425649/22370168/f9de573a-e487-11e6-9d30-6776d46ecfb9.png)

**Comment by TeodorKolev** [comment]
Man, please check link of your screenshot and search for append to body

**Comment by TeodorKolev** [comment]
Appends the popover to a specific element. Example: container: 'body'. This option is particularly useful in that it allows you to position the popover in the flow of the document near the triggering element - which will prevent the popover from floating away from the triggering element during a window resize.

**Comment by TeodorKolev** [comment]
[HERE](https://v4-alpha.getbootstrap.com/components/popovers/#options)

**Comment by TeodorKolev** [comment]
do you see any custom logic [here](http://plnkr.co/edit/jLThSTrLUapAG8OLW44m?p=preview)?

**Comment by mattlewis92** [comment]
That's describing something different from the example you gave here: http://newyork2017.findevr.com/#partners

In that example the popover is auto positioned depending on the screen resolution.

The reason that tooltip example you gave works is because they don't position the tooltip to the left, if you do that the same problem occurs: http://plnkr.co/edit/6WeWgEa64xokD85Kn3Sz?p=preview

**Comment by TeodorKolev** [comment]
In first example I see only this code:
```
setUpTooltips: function () {
			var $hovercard = $('.hovercard');
			$hovercard.each(function(){
				var $this = $(this);
				
				$this.popover({
					content: $this.find('.hoverdata').html(),
					html: true,
					trigger: 'manual',
					placement: 'bottom'
				}).on ('click', function () {
				  	if ( ! $this.hasClass( 'logo-hidden' )) {
						$this.popover('show');
					}	
				}).on('mouseenter', function () {
					if ( ! $this.hasClass( 'logo-hidden' )) {
			        	$this.popover('show');
			        }	
			        $this.siblings('.popover').on('mouseleave', function () {
			            $this.popover('hide');
			        });
			    }).on('mouseleave', function () {
			        setTimeout(function () {
			            if (!$('.popover:hover').length) {
			                $this.popover('hide');
			            }
			        }, 100);
    			});
	    			
			});
		},
```

**Comment by TeodorKolev** [comment]
The difference is that in example popover is position to bottom and it is always proper. In that repo when it is also to bottom is hided. It is not proper

**Comment by mattlewis92** [comment]
If you check the CSS source you can see they're using CSS to fix the positioning for their site e.g.
```
@media (min-width: 992px) {
  .popover {
    max-width: 430px;
  }
}
```

There's probably also some other styling they're applying as well.

**Comment by TeodorKolev** [comment]
what width have to do with position
