### ISSUE TITLE
Confirmation popover in combination with stop event propagation

### ISSUE THREAD

**Issue by kubica** [mattlewis92/angular-confirmation-popover#39]
I have a list with links to several subjects and each of list-items contains a button (for delete) on top of it. If you call the delete button you get two click actions. I use the solution from [stackoverflow](http://stackoverflow.com/questions/35274028/stop-event-propagation-in-angular-2) to solve it (the background action is cancelled).

Now i want to use the confirmation-popover. **Problem I** is that when i click the delete button it directly links me to the subject. I can avoid this by adding `(click)="$event.stopPropagation(); false"` to my delete button. **Problem II** is that the redirect to the subject is still triggered when i click on submit/cancel. I can not add `$event.stopPropagation(); false` to `(confirm)` or `(cancel)` due to undefined. I also tried a redirect with `router.navigateByUrl('/')` in `(confirm)` and `(cancel)`. Still not working.

Is there any ideas how i can get it working? Why does `(confirm)` and `(cancel)` trigger the background action _again_?

Thanks for reading!

**Comment by mattlewis92** [comment]
I've exposed the click events now on the click / confirm outputs. So you should be able to do
```
(confirm)="$event.clickEvent.preventDefault(); $event.clickEvent.stopPropagation(); onConfirm()"
```

It sounds like you have a bug in your app though, having global click events on every button is generally considered bad practise, maybe you could create a directive in your app whereby any child elements that are clicked don't trigger the background action.
