### ISSUE TITLE
event in (confirm) directive doesnt have stopPropagation() method

### ISSUE THREAD

**Issue by fzunigad** [mattlewis92/angular-confirmation-popover#43]

**Comment by mattlewis92** [comment]
It's because `$event` isn't the click event, but a wrapper over it. You need to do `$event.clickEvent .stopPropagation()` instead. Source: https://github.com/mattlewis92/angular-confirmation-popover/blob/master/src/confirmationPopoverWindow.component.ts#L31 Hope that helps!
