### ISSUE TITLE
angular-confirmation-popover problem with primeng dataTable

### ISSUE THREAD

**Issue by abadakhshan** [mattlewis92/angular-confirmation-popover#45]
hi
When I use angular-confirmation-popover  inside  primeng dataTable as column template
popup is shown inside datatable .
for  example  if table contains only one row(low height) , popup hides inside dattable and user must scroll datatable to click on confirm or cancel.

**Comment by abadakhshan** [comment]
one solution is set appendToBody to true

but another problem
if set appendToBody  in ConfirmationPopoverModule.forRoot()
popup dosent display in correct location

**Comment by mattlewis92** [comment]
Sorry I'm not sure I can help you much, are you able to make a simple repo / plunker that reproduces your issue please? Thanks!

**Comment by abadakhshan** [comment]
Please check 
[pull request](https://github.com/mattlewis92/angular-confirmation-popover/pull/46)

for  set "appendToBody" in "ConfirmationPopoverModule.forRoot()"

Thanks!
