### ISSUE TITLE
validation before popup

### ISSUE THREAD

**Issue by dvaughn88** [mattlewis92/angular-confirmation-popover#48]
Thanks for the component, very helpful. 
I am trying to prevent the popup component until the user gets through some form validation. I set the  [isOpen]="confirmDialogOpened" model item to false upon init and was thinking I would set it to true if they pass validation. It seems though that the click event handler is just a toggle and does not pay attention to the isOpen value. 

Is there something I need to do with the event? I've tried to prevent default etc but it doesn't seem to work. Thx for any help.

       <button
          class="btn"
          mwlConfirmationPopover
          [title]="title"
          [message]="message"
          [confirmText]="confirmText"
          [cancelText]="cancelText"
          [placement]="placement"
          (confirm)="confirmClicked = true"
          (cancel)="cancelClicked = true"
          confirmButtonType="danger"
          cancelButtonType="default"
          [isOpen]="confirmDialogOpened"
          (click)="editItemValidation(); confirmClicked = false; cancelClicked = false"
          [appendToBody]="true">
          Save
        </button>

**Comment by mattlewis92** [comment]
You should be able to use the `[isDisabled]` input to disable the auto opening of the popup:
```
<button
      class="btn"
      mwlConfirmationPopover
      [title]="title"
      [message]="message"
      [confirmText]="confirmText"
      [cancelText]="cancelText"
      [placement]="placement"
      (confirm)="confirmClicked = true"
      (cancel)="cancelClicked = true"
      confirmButtonType="danger"
      cancelButtonType="default"
      [isOpen]="confirmDialogOpened"
      [isDisabled]="!confirmDialogOpened"
      (click)="editItemValidation();"
      [appendToBody]="true">
      Save
    </button>
```

Hope that helps! 😄

**Comment by dvaughn88** [comment]
It did, thanks!
