### ISSUE TITLE
Take into account scroll position when showing popup.

### ISSUE THREAD

**Issue by HenricusL** [mattlewis92/angular-confirmation-popover#49]
If used within an element with a vertical scrollbar and vertical scroll position is not top, the confirmation popup window position is not correct. Distance to correct position is the same as vertical scroll position from top. Probably the same issue with horizontal scrollbar.

**Comment by mattlewis92** [comment]
You can use the `[appendToBody]="true"` option to work around this.

**Comment by HenricusL** [comment]
Works perfectly. Thanks.
