### ISSUE TITLE
NPM Install?

### ISSUE THREAD

**Issue by landervs** [mattlewis92/angular-confirmation-popover#50]
When i run the command _npm install --save angular-confirmation-popover_ then i have almost a blank directory in @nodes_mdoules/angular-confirmation-popopver.

I only have those files: changelog, license, readme and package.json.

Is the package incomplete or am i doing something wrong?

Thanks a bunch,

Lander

**Comment by mattlewis92** [comment]
You should have a `dist` folder as well: https://unpkg.com/angular-confirmation-popover@3.1.1/ If that's not there then it sounds like a bug with npm. Try doing `npm i -g npm@latest` to install the latest version and try again 😄

**Comment by landervs** [comment]
Thanks so much, indeed you were right, it was a bug with NPM. Its fixed with updating NPM! Thanks again.
