### ISSUE TITLE
Support Bootstrap 4 beta

### ISSUE THREAD

**Issue by justin1291** [mattlewis92/angular-confirmation-popover#51]
After updating to bootstrap 4 beta, template styles aren't quite correct.

See the image below:

![image](https://user-images.githubusercontent.com/22896326/29297110-8bd2b37a-8113-11e7-819e-a84d943ac378.png)

**Comment by mattlewis92** [comment]
I've just published 3.2.0 which adds support for the latest bootstrap beta 😄

**Comment by justin1291** [comment]
@mattlewis92 Thank you so much. I got 3.2 and it works perfectly.
