### ISSUE TITLE
Action for close popover on document click

### ISSUE THREAD

**Issue by kubica** [mattlewis92/angular-confirmation-popover#54]
Hey, as far as i noticed the `(cancel)` event is only executed when the cancel button is pressed.
Is there any opportunity to detect if the popover is closed on document click or closed generally (pressing cancel button or click document)?

**Comment by mattlewis92** [comment]
You can use the [`(isOpenChange)`](https://github.com/mattlewis92/angular-confirmation-popover/blob/master/src/confirmationPopover.directive.ts#L146) output to detect when the popover is opened or closed. `$event` will be true or false depending on if the popover is opened or closed. Hope that helps! 😄
