### ISSUE TITLE
no exported member 'InjectionToken'

### ISSUE THREAD

**Issue by iamntg** [mattlewis92/angular-confirmation-popover#55]
I am getting the error of InjectionToken

ERROR in D:/Work/Moduurn/moduurnweb/node_modules/angular-confirmation-popover/dist/esm/src/confirmationPopover.module.d.ts (1
,31): Module '"<root-folder>/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

**Comment by mattlewis92** [comment]
Sounds like you're trying to use this lib with angular 2, you need 4.0+
