### ISSUE TITLE
[title] attribute renaming ?

### ISSUE THREAD

**Issue by vanackere** [mattlewis92/angular-confirmation-popover#56]
Hi,

 Thank you for your very useful directive. Would you consider renaming the title attribute from your directive to something else (like confirm-title) ?
The current attribute conflicts with the common title attribute used for tooltips (in buttons usually) and I found no other way than wrapping the button in a <span> block so far.

Regards,

**Comment by ChaudhryAtif** [comment]
Have you tried Angular JS way of setting the title?
https://github.com/mattlewis92/angular-bootstrap-confirm#title

**Comment by vanackere** [comment]
Hi,

  I just tried putting both [title] and data-title on the same element doesn't seem to work properly.
Even if it did work, I also think that it would be very confusing...
If you're willing to break the current api of your component (I agree that it's not ideal but I cannot think of a better solution), renaming 'title' to 'confirmTitle' would properly solve this issue.

**Comment by ChaudhryAtif** [comment]
Not sure what/how you are trying, but this is working for me:
```
<button
        class="btn btn-default"
        mwlConfirmationPopover
        data-title="Popover title"
        message="Popover description"
        placement="bottom"
        (confirm)="confirmClicked = true"
        (cancel)="cancelClicked = true">
    Click me!
</button>
```

![image](https://user-images.githubusercontent.com/7082580/31568404-cf428338-b039-11e7-8185-6677f9264116.png)

If that doesn't work for you, provide an example.

**Comment by vanackere** [comment]
Sorry for not being clear. Here is a real case where I had to use an enclosing span element to be able to have a tooltip on a button with your popover directive:
```
<span mwlConfirmationPopover placement="left" [confirmText]="tr.ConfirmDeleteButton()" confirmButtonType="danger" [cancelText]="tr.CancelDeleteButton()" [message]="tr.DeleteUserAlert()" [title]="tr.DeleteUserTitle({User:user.Email})" (click)="$event.stopPropagation()" (confirm)="remove(user); $event.stopPropagation();">
  <button [title]="tr.DeleteUserEnabledTooltip()" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i>
  </button>
</span>
```

**Comment by vanackere** [comment]
Hi, 

 Feel free to close this issue if you don't intend to fix this (and I'll fork your plugin locally instead...).

**Comment by ChaudhryAtif** [comment]
@vanackere I'm not the creator of the plugin. Was just trying to help.

Please provide a plunker to demo the issue and perhaps I, or someone else, will be able to help.

**Comment by mattlewis92** [comment]
Please give 3.3.0 a try, I've added a `popoverTitle` attribute you can use instead. Hope that helps!
