### ISSUE TITLE
Build Error when deploying

### ISSUE THREAD

**Issue by jbloem9** [mattlewis92/angular-confirmation-popover#63]
When running my solution locally it works great.  However when trying to build and push the site to the test server I am getting the following error;

EXEC : [0m[1m[31mERROR in error : Metadata version mismatch for module D:/BuildMaster/_SVCTMP/_E53707/_D188/src/AuctionX.Web.Ui.Ng/node_modules/angular-confirmation-popover/dist/esm/src/index.d.ts, found version 4, expected 3, resolving symbol AgenciesModule in D:/BuildMaster/_SVCTMP/_E53707/_D188/src/AuctionX.Web.Ui.Ng/src/app/agencies/agencies.module.ts, resolving symbol AgenciesModule in D:/BuildMaster/_SVCTMP/_E53707/_D188/src/AuctionX.Web.Ui.Ng/src/app/agencies/agencies.module.ts, resolving symbol AgenciesModule in D:/BuildMaster/_SVCTMP/_E53707/_D188/src/AuctionX.Web.Ui.Ng/src/app/agencies/agencies.module.ts[39m[22m[0m [D:\BuildMaster\_SVCTMP\_E53707\_D188\src\AuctionX.Web.Ui.Ng\AuctionX.Web.Ui.Ng.csproj]

My package.json file is attached.

[packageJson.txt](https://github.com/mattlewis92/angular-confirmation-popover/files/1489935/packageJson.txt)

**Comment by pushpender-techmarbles** [comment]
I'm also having same issue, locally.

My package.json is also attached.
[packageJson.txt](https://github.com/mattlewis92/angular-confirmation-popover/files/1490536/packageJson.txt)

**Comment by mattlewis92** [comment]
Oh, apparently if you compile a library with ng5, its not compatible with ng4: https://github.com/angular/angular/issues/19607

Pushing a fix now 😄

**Comment by mattlewis92** [comment]
Fixed in 3.4.0
