### ISSUE TITLE
isOpen is not opening the confirmation popover

### ISSUE THREAD

**Issue by seanlawrenz** [mattlewis92/angular-confirmation-popover#65]
The documentation is spotty on this, but I cannot get the popover to open on isOpen

**Comment by mattlewis92** [comment]
Can you provide a minimal plunker, stackblitz etc that reproduces this? It works in the tests: https://github.com/mattlewis92/angular-confirmation-popover/blob/master/test/angular-confirmation-popover.spec.ts#L302-L307

**Comment by seanlawrenz** [comment]
Here you go:
https://angular-mwzq2z.stackblitz.io

I might not understand how the isOpen should be used, but by the documentation, I should be able to open it through an event.

**Comment by mattlewis92** [comment]
Thanks for the repro! It should be fixed now in `3.4.2` 😄
