### ISSUE TITLE
opening popover on (mouseover) in a ngFor

### ISSUE THREAD

**Issue by neo-xy** [mattlewis92/angular-confirmation-popover#66]
hi, having trouble to implement popover in ngFor loop when tring to trigger it trough binding to (mouseover) 
my code(simplified):

`  <button *ngFor="let l of list"
          class="btn btn-default"
          mwlConfirmationPopover
          [popoverTitle]="popoverTitle"
          [popoverMessage]="popoverMessage"
          placement="bottom"
          [isOpen]="mouseover"
          (mouseover)="mouseover=true"
          (mouseleave)="mouseover=false"
          (confirm)="confirmClicked = true"
          (cancel)="cancelClicked = true">
    Click me!
  </button>`

what's happening is that popover shows up ofc for every button at once ,
what is the correct whey to aproach that. so that popover shows for only one button at a time..?

**Comment by mattlewis92** [comment]
It's because `[isOpen]="mouseover"` is bound to a single variable, you should bind it to something unique like `[isOpen]="list[mouseover]"` instead. Hope that helps!

**Comment by neo-xy** [comment]
great, ty sir
