### ISSUE TITLE
Button style

### ISSUE THREAD

**Issue by dland512** [mattlewis92/angular-confirmation-popover#68]
Is there any way to change the button class from `btn-danger` to `btn-primary` for just one instance of the popover?

**Comment by mattlewis92** [comment]
You can use the [`confirmButtonType`](https://mattlewis92.github.io/angular-confirmation-popover/docs/directives/ConfirmationPopoverDirective.html#confirmButtonType) and [`cancelButtonType`](https://mattlewis92.github.io/angular-confirmation-popover/docs/directives/ConfirmationPopoverDirective.html#cancelButtonType) inputs for this.

**Comment by dland512** [comment]
Totally missed that in the docs. Thank you!
