### ISSUE TITLE
expect a little help not an issue 

### ISSUE THREAD

**Issue by asachanxxx** [mattlewis92/angular-confirmation-popover#69]
Hi 

i need to notify when confirm button clicked inside angular 
actually my case is i have a form with 2 buttons 
1. insert 
2. Update

i already integrate this popover to the buttons. my case is i cannot get notify when each button clicked individually for 2 stages (Confirm , cancel) .

a little help would be appreciated

**Comment by asachanxxx** [comment]
Alright guys i figure it out. 
call the event
 (confirm)="confirm('true',val)"

**Comment by ChaudhryAtif** [comment]
@asachanxxx If this is resolved, go ahead and close this.

**Comment by mattlewis92** [comment]
Glad you got it sorted 😄
