### ISSUE TITLE
Confirmation doeskin popup using ngbDropdownMenu

### ISSUE THREAD

**Issue by ozsdev** [mattlewis92/angular-confirmation-popover#74]
Hi,

Thank you for this useful directive.
I am trying to use it along with ngbDropdownMenu and the confirmation popup is not showing, any suggestion please?

<div class="btn-group" ngbDropdown role="group" aria-label="Button group with nested dropdown">
                        <a ngbDropdownToggle>
                            <i class="fa fa-times text-red"></i>
                        </a>

                        <div class="dropdown-menu" ngbDropdownMenu>
                            <button
                                *ngFor="let flow of certificationPlan.flows"
                                class="dropdown-item"
                                mwlConfirmationPopover
                                [popoverTitle]="'Delete Token'"
                                [popoverMessage]="'Are you sure?'"
                                placement="left"
                                (confirm)="removeComp(flow)">
                                Index: [{{flow.index}}] | ID: [{{flow.flowId}}]
                            </button>
                        </div>
                    </div>

Thanks.

**Comment by mattlewis92** [comment]
I think this is because the dropdown gets closed when you select the option, so the popover has no host element to bind on and won't get shown. If you set `[autoClose]="false"` on the dropdown menu then it should probably fix it.
