### ISSUE TITLE
Angular 8

### ISSUE THREAD

**Issue by clabough** [mattlewis92/angular-confirmation-popover#80]
Hope this doesn't require Bronze level.

# npm install
npm WARN angular-confirmation-popover@4.2.0 requires a peer of @angular/common@>=5.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-confirmation-popover@4.2.0 requires a peer of @angular/core@>=5.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by mattlewis92** [comment]
Please send a pull request 😄 You should just need to update the peer dependency here: https://github.com/mattlewis92/angular-confirmation-popover/blob/master/package.json#L117-L118
